config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  resources :users, only: [:new, :create, :show, :index]
  resources :events, only:[:new, :create, :show, :index]
  resources :attendees, only:[:create]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :date, :description, presence: true
  scope :past_events, -> { where('date < ?', Date.today) }
  scope :future_events, -> { where('date >= ?', Date.today) }
  has_many :event_attendences, foreign_key: :attended_event_id
  has_many :event_attendees, through: :event_attendences, source: :event_attendence
  belongs_to :creator, class_name: 'User'
end

app/models/event_attendence.rb
class EventAttendence < ApplicationRecord
  belongs_to :event_attendence, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :event_attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  before_validation :downcase
  validates :user_name, presence: true
  validates_uniqueness_of :user_name

  has_many :event_attendences, foreign_key: :event_attendence_id
  has_many :attended_events, through: :event_attendences
  has_many :created_events, foreign_key: :creator_id, class_name: 'Event', dependent: :destroy

  def downcase
    user_name&.downcase!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :signed_up?, :past_events
  def current_user
    session[:user_id] ? User.find(session[:user_id]) : false
  end

  def signed_up?
    current_user ? true : false
  end

  def logged_in?
    current_user ? true : false
  end

  def past_events
    Event.where('date < ?', Date.today)
  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  def create
    event_id = params[:event_id]
    @attendee = EventAttendence.find_or_initialize_by(event_attendence_id: current_user.id, attended_event_id: event_id)
    redirect_to root_path if @attendee.save
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :current_user, only: %i[new create]

  include EventsHelper

  def new
    @event = Event.new
  end

  def create
    @user = current_user
    @event = @user.created_events.build(event_params)
    if @event.save
      redirect_to events_path
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def index
    @past_events = Event.past_events
    @upcoming_events = Event.future_events
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(user_name: params[:session][:user_name].downcase)
    if user
      session[:user_id] = user.id
      redirect_to user
    else
      flash.now[:error] = 'Username does not exist!'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    @user = nil
    redirect_to root_path, notice: 'You have successfully logged out.' if @user.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash.now[:errors] = @user.errors.full_messages
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @created_events = @user.created_events
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:user_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def event_params
    params.require(:event).permit(:name, :description, :date)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def past_attended_events
    current_user.attended_events.where('date <= ?', Date.today)
  end

  def future_events
    current_user.attended_events.where('date > ?', Date.today)
  end

  def capitalize_user_name
    current_user.user_name.capitalize
  end
end

app/views/attendees/_attendence_form.html.erb
<% unless current_user.attended_events.include?(event) %>
  <%= form_with(model: @event_attendence, url: attendees_path, local: true) do |form| %>
    <div class="forms mb-4">
      <%= form.hidden_field :event_id, class: 'form-control', value: event.id %>
      <div class="actions">
        <%= form.submit 'Attend event', class: 'btn btn-primary mt-2' %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/events/index.html.erb
<div class = 'container my-3'>
  <h1 class = 'font-weight:bolder'>Upcoming events</h1>
  <div class = 'row'>
    <% @upcoming_events.each do |event| %>
      <div class="card col-3 bg-info text-white font-weight:bolder mt-2" style="width: 18rem;">
        <div class="card-body">
          <h5 class="card-title"><%= event.name %></h5>
          <h6 class="card-subtitle mb-2"><%= event.date %></h6>
          <p class="card-text"><%= event.description %></p>
          <% if logged_in?%>
            <%= render 'attendees/attendence_form', event: event%>
          <% end %>
          <%= link_to 'Show', event, class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
  <hr>
  <h1>Past events</h1>
  <div class = 'row'>
    <% @past_events.each do |event| %>
      <div class="card col-3 bg-info text-white font-weight:bolder" style="width: 16rem;">
        <div class="card-body">
          <h5 class="card-title"><%= event.name %></h5>
          <h6 class="card-subtitle mb-2"><%= event.date %></h6>
          <p class="card-text"><%= event.description %></p>
          <%= link_to 'Show', event, class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h1 class = 'text-center mt-5 font-weight-bolder'>Create an Event</h1>
<div class = 'd-flex justify-content-center'>
<%= form_with(model: @event, local: true) do |f|%>
  <%= f.label :name, class: 'font-weight-bolder mb-2'%>
  <%= f.text_field :name, class: 'mb-2'%><br>
  <%= f.label :date, class: 'mb-2 font-weight-bolder'%>
   <h3>Format: 'yyyy-mm-dd'</h3>
   <%= f.text_field :date %>
   <%= f.label :description, class: 'my-2 font-weight-bolder'%>
  <%= f.text_field :description %><br>
  <div class = 'd-flex justify-content-center mt-3'>
  <%= f.submit "Submit", class: 'btn btn-primary font-weight-bolder' %>
  </div>
<% end %>
<div>

app/views/events/show.html.erb
<div class = 'd-flex justify-content-center my-5'>
  <div>
  <h2 class = 'font-weight-bolder mb-3 bg-primary'>Attending <%= @event.name %></h2>
    <div class = 'col-4'>
  
      <% @event.event_attendees.each do |attendee| %>
        <ul>
        <li><h2 class = 'font-weight-bolder'><%= attendee.user_name %></h2></li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand text-body" href="#">EVENTISE</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto ml-lg-5">
          <li class="nav-item">
            <%= link_to 'All Events', events_path, class: 'nav-link'%>
          </li>
          <% if logged_in? || signed_up? %>
            <li class="nav-item">
              <%= link_to current_user.user_name.capitalize, current_user, class: 'nav-link'%>
            </li>
            <li class="nav-item">
              <%= link_to 'Create Event', new_event_path, class: 'nav-link'%>
            </li>
          <% end %>
        </ul>
        <% if logged_in? || signed_up? %>
          <%= link_to 'Sign Out', logout_path, class:'btn btn-secondary font-weight-bold', :method => :delete%>
        <% end %>
        <% unless logged_in? || signed_up? %>
          <%= link_to 'Sign Up', new_user_path, class:'btn btn-secondary font-weight-bold mr-lg-5' %>
          <%= link_to 'Sign In', login_path, class:'btn btn-secondary font-weight-bold' %>
        <% end %>
      </div>
    </nav>
    <% flash.each do |key, msg| %>
      <%= msg %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
All Members
<% @users.each do |user| %>
<h2><%= user.user_name%></h2>
<% end %>

app/views/users/new.html.erb
<div class = 'd-flex justify-content-center mt-5'>
  <div>
    <h1 class = 'text-center font-weight-bolder'>Sign Up</h1>
    <%= form_with(model: @user, local: true) do |f|%>
      <%= f.label :name, class: 'font-weight-bolder align-middle'%>
      <%= f.text_field :user_name %><br>
      <div class = 'd-flex justify-content-center'>
        <%= f.submit "Submit", class: 'btn btn-primary mt-2' %>
      </div>
    <% end %>
  <div>
</div>

app/views/users/show.html.erb
<div class = 'd-flex justify-content-center my-5'>
  <div>
  <h1 class = 'text-center font-weight-bolder mb-3'><%= capitalize_user_name %>'s Account</h1>
    <div class = 'row'>
      <div class = 'col-4 bg-info'>
        <h1 class = 'font-weight-bolder'> Created Events </h1>
        <%if @created_events.any?%>
          <% @created_events.each do |e| %>
            <ul>
              <li>
                <%= e.name %>
              </li>
            </ul>
          <% end %>
        <% end %>
      </div>
      <div class = 'col-4 bg-success'>
        <h1 class = 'font-weight-bolder'> Events Attended In Past</h1>
        <%if current_user.attended_events.any?%>
          <% past_attended_events.each do |e| %>
            <ul>
              <li>
                <%= e.name %>
              </li>
            </ul>
          <% end %>
        <% else %>
          <h2>No past attended events</h2>
        <% end %>
      </div>
      <div class = 'col-4 bg-secondary'>
        <h1 class = 'font-weight-bolder'>Upcoming Events</h1>
        <% if current_user.attended_events.any?  %>
          <% future_events.each do |e| %>
            <ul>
              <li>
                <%= e.name %>
              </li>
            </ul>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>